# Generated by Django 5.0.4 on 2024-04-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_regnumber', models.CharField(max_length=255)),
                ('driver_fullname', models.CharField(max_length=255)),
                ('driver_contact', models.CharField(max_length=255)),
                ('deployment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('specialisation', models.CharField(max_length=254)),
                ('on_duty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('national_id', models.CharField(default='NULL', max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(default='NULL', max_length=255)),
                ('address', models.CharField(default='NULL', max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('chronic_diseases', models.CharField(max_length=255)),
                ('nok_name', models.CharField(default='NULL', max_length=255)),
                ('nok_relationship', models.CharField(default='NULL', max_length=255)),
                ('nok_contact', models.CharField(default='NULL', max_length=255)),
                ('admitted', models.CharField(default='NULL', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('type_of_ward', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('addmitted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('prescription', models.CharField(max_length=255)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_fullname', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('paid', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_by', models.TextField()),
                ('test', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('test_results', models.TextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Addmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.IntegerField(default=0)),
                ('date_of_admission', models.DateField(default='NULL', max_length=255)),
                ('date_of_discharge', models.DateField(max_length=255, null=True)),
                ('status', models.CharField(default='NULL', max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.ward')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doc_id', 'date', 'time'), name='unique booking for doctors'),
        ),
    ]
